[package]
name = "zellij-todo"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"

[dependencies]
zellij-tile = "0.43"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
